### ISSUE TITLE
KeyError: "None of ['index'] are in the columns"

### ISSUE THREAD

**Issue by seanexp** [fgenie/rims_minimal#12]
https://github.com/fgenie/rims_minimal/blob/d0b4f2b46bc9acb6b0df2fe633cbc94d7c3c3e9a/src/run_inference.py#L258-L260

gsm 데이터셋에서는 index 가 있었던 것 같은데 다른 데이터셋에서는 있다고 보장하기는 힘드니 처리를 해주는 게 좋을 것 같습니다.

```
df = pd.DataFrame(records)
    if "index" in df.columns:
        df = df.set_index("index", drop=False)
```

정도가 어떨까 싶네요

**Comment by seanexp** [comment]
@fgenie @jason9693

**Comment by fgenie** [comment]
작업중입니다. 참고하고 완료 후 닫을게요.
